runtime: nodejs22
service: online-games

automatic_scaling:
  min_instances: 0
  max_instances: 1

build_env_variables:
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_WS_URL: "wss://api.icogenx.com/ws"

env_variables:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_WS_URL: "wss://api.icogenx.com/ws"

handlers:
  - url: /.*
    script: auto
    secure: always