runtime: custom
env: flex
service: backend

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

network:
  session_affinity: true

env_variables:
  RUST_LOG: "info"