export interface GameVariantMetadata {
  id: string;
  name: string;
  icon: string;
  desc: string;
  path: string;
  rulesTitle?: string;
  rules?: string[];
  tips?: string[];
  previewSteps?: string[];
}

export interface GameCatalogItem {
  id: string;
  gameType: string;
  name: string;
  icon: string;
  description: string;
  players: string;
  category: string;
  badgeClass: string;
  gradient: string;
  rulesTitle: string;
  rules: string[];
  tips: string[];
  previewSteps: string[];
  variants?: GameVariantMetadata[];
  playerCount: number;
  playerLabel: string;
  tags: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  estimatedTime: string;
  featured?: boolean;
  isComingSoon?: boolean;
}

const TIC_TAC_TOE_VARIANTS: GameVariantMetadata[] = [
  {
    id: 'classic',
    name: 'Classic',
    icon: 'tic-tac-toe-classic',
    desc: 'Normal 3x3. Draws are possible.',
    path: '/games/tic-tac-toe/classic',
    rulesTitle: 'Classic Rules',
    rules: ['Take turns placing marks on the 3x3 board.', 'Make three in a row horizontally, vertically, or diagonally.', 'A full board without a line ends in a draw.'],
    tips: ['Corners give you more fork chances than edges.', 'Block a two-in-a-row before building your own threat.'],
    previewSteps: ['Place X/O', 'Block forks', 'Make a line'],
  },
  {
    id: 'disappearing',
    name: 'Disappearing',
    icon: 'tic-tac-toe-disappearing',
    desc: 'Keep 4 marks in play. Your oldest vanishes on the 5th move.',
    path: '/games/tic-tac-toe/disappearing',
    rulesTitle: 'Disappearing Rules',
    rules: ['Each player can keep only four marks on the board.', 'When you place a fifth mark, your oldest mark disappears.', 'Make three in a row while planning around the vanishing order.'],
    tips: ['Track your oldest mark before setting up a line.', 'Sometimes a disappearing mark opens the winning lane.'],
    previewSteps: ['Place mark', 'Oldest fades', 'Time the line'],
  },
  {
    id: 'joker',
    name: 'Joker Cell',
    icon: 'tic-tac-toe-joker',
    desc: 'One cell is gold and acts as X and O.',
    path: '/games/tic-tac-toe/joker',
    rulesTitle: 'Joker Rules',
    rules: ['One highlighted cell counts as both X and O even when empty.', 'A winning line through the Joker ends the game immediately.', 'Both players can use the Joker as part of their line.'],
    tips: ['Treat every line through the Joker as urgent.', 'Win by controlling the cells around the Joker, not just the Joker itself.'],
    previewSteps: ['Spot Joker', 'Build around it', 'Strike through'],
  },
  {
    id: 'gobblet',
    name: 'Gobblet Gobblers',
    icon: 'tic-tac-toe-gobblet',
    desc: 'Small, medium, and large pieces can cover smaller ones.',
    path: '/games/tic-tac-toe/gobblet',
    rulesTitle: 'Gobblet Rules',
    rules: ['Each player has small, medium, and large pieces.', 'Larger pieces can cover smaller pieces.', 'Uncovering a piece can reveal an older threat.'],
    tips: ['Do not cover a line unless you know what is underneath.', 'Save a large piece for late defense.'],
    previewSteps: ['Choose size', 'Cover pieces', 'Reveal threats'],
  },
  {
    id: 'gravity',
    name: 'Gravity',
    icon: 'tic-tac-toe-gravity',
    desc: 'Drop marks into columns and let them fall to the bottom.',
    path: '/games/tic-tac-toe/gravity',
    rulesTitle: 'Gravity Rules',
    rules: ['Pick a column instead of a cell.', 'Your mark falls to the lowest open slot in that column.', 'Make three in a row after gravity settles the board.'],
    tips: ['Count what your drop gives the opponent above it.', 'Middle columns create more diagonal pressure.'],
    previewSteps: ['Drop mark', 'Stack columns', 'Connect three'],
  },
  {
    id: 'bidding',
    name: 'Bidding',
    icon: 'tic-tac-toe-bidding',
    desc: 'Spend chips in auctions to win the right to place.',
    path: '/games/tic-tac-toe/bidding',
    rulesTitle: 'Bidding Rules',
    rules: ['Bid chips to win the right to place the next mark.', 'Higher bid wins the turn and spends those chips.', 'Make three in a row before your chip economy runs dry.'],
    tips: ['Save chips when a square is not urgent.', 'Spend hard when one move creates or blocks a win.'],
    previewSteps: ['Bid chips', 'Win turn', 'Place mark'],
  },
  {
    id: 'blind',
    name: 'Blind Memory',
    icon: 'tic-tac-toe-blind',
    desc: 'Call numbered squares from memory. Occupied calls lose turns.',
    path: '/games/tic-tac-toe/blind',
    rulesTitle: 'Blind Rules',
    rules: ['Choose numbered squares from memory.', 'Calling an occupied square wastes your turn.', 'Remember the hidden board well enough to make three in a row.'],
    tips: ['Replay the board in your head after every turn.', 'Use corner numbers as anchors.'],
    previewSteps: ['Memorize', 'Call square', 'Reveal mark'],
  },
];

const SMART_FOUR_VARIANTS: GameVariantMetadata[] = [
  {
    id: 'classic',
    name: 'Classic 3D',
    icon: 'smart-four-classic',
    desc: 'Classic 3D Connect Four. Connect 4 in any direction in a 5x5x5 space.',
    path: '/games/smart-four',
    rulesTitle: 'Classic 3D Rules',
    rules: [
      'Take turns placing your tokens in any column of the 5x5 grid.',
      'Tokens stack up to a maximum height of 5.',
      'The first player to align four tokens in a straight line horizontally, vertically, or diagonally in 3D space wins the game!'
    ],
    tips: [
      'Look out for vertical columns; it is easy to forget the vertical dimension.',
      'Set up dual-threat paths that fork across diagonal planes.',
      'Control the central 3x3 cells to maximize your connection directions.'
    ],
    previewSteps: ['Stack 5 high', 'Scan 3D space', 'Connect 4'],
  },
  {
    id: 'topple',
    name: 'Topple',
    icon: 'smart-four-topple',
    desc: 'Wobbly balancing board. Roll the die to place tokens on matching rings, scoring points without causing a collapse!',
    path: '/games/smart-four/topple',
    rulesTitle: 'Topple Rules',
    rules: [
      'Start your turn by rolling a 6-sided die.',
      'Place your token on a cell in the ring matching your roll (Ring 1 = center, Ring 5 = corners). A roll of 6 is Wild (place anywhere).',
      'Each placed piece adds weight (height * 0.5 + 1.0) and exerts torque on the wobbly board.',
      'Earn points based on the Ring level of your placement (1 to 5 pts) and bonus points for completing lines of 3 (+3 pts) or 4 (+5 pts).',
      'If the balance tilt exceeds the safety threshold (11.5), the board TOPPLES and you instantly lose!'
    ],
    tips: [
      'Try to counter-balance your opponent\'s weights by placing on the opposite side.',
      'Stacking pieces higher increases the weight and torque multiplier.',
      'Earn line completion bonuses early before the board gets too wobbly.'
    ],
    previewSteps: ['Roll the die', 'Place on Ring', 'Balance torque'],
  },
];

export const GAME_CATALOG: GameCatalogItem[] = [
  {
    id: 'tic-tac-toe',
    gameType: 'tic_tac_toe',
    name: 'Tic-Tac-Toe Variants',
    icon: 'tic-tac-toe',
    description: 'Play Classic, Gobblet, Gravity, Bidding, Blind, and more Tic-Tac-Toe twists.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    rulesTitle: 'Tic-Tac-Toe Rules',
    rules: TIC_TAC_TOE_VARIANTS[0].rules || [],
    tips: ['Look for moves that create two threats at once.', 'Center is powerful because it touches four winning lines.'],
    previewSteps: ['Pick variant', 'Place marks', 'Win the line'],
    variants: TIC_TAC_TOE_VARIANTS,
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '2-5 min',
    tags: ['strategy', 'couples', 'classic'],
    featured: true,
  },
  {
    id: 'shut-the-box',
    gameType: 'shut_the_box',
    name: 'Dice Tug-of-War',
    icon: 'shut-the-box',
    description: 'Roll, advance your cards, and automatically pull matching opponent cards back.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-orange',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    rulesTitle: 'Dice Tug-of-War Rules',
    rules: ['Roll one die, then choose unopened cards that add up to the roll.', 'Your selected cards move forward automatically.', 'Exact matching opponent cards move back automatically.', 'First player to move all six cards forward wins.'],
    tips: ['Pick the exact matching number when you want to pull an opponent card back.', 'A single high card can be stronger than two low cards if it blocks the opponent.', 'Check the opponent row before choosing equal-sum combinations.', 'If the opponent has 3 open, choosing your 3 sends their 3 back.'],
    previewSteps: ['Roll die', 'Pick sum', 'Push track'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '3-6 min',
    tags: ['strategy', 'couples', 'dice'],
    featured: false,
  },
  {
    id: 'code-guess',
    gameType: 'code_guess',
    name: 'Code Breaker',
    icon: 'code-guess',
    description: 'Lock secret 4-digit codes or player-chosen number targets, then crack your opponent first.',
    players: '2 Players',
    category: 'Logic',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    rulesTitle: 'Code Breaker Rules',
    rules: ['Each player locks in a secret 4-digit code.', 'On your turn, submit one 4-digit guess.', 'Green means right digit and right spot; yellow means right digit, wrong spot.', 'Crack the opponent code first to win.'],
    tips: ['Use early guesses to test different digits, not just positions.', 'Repeated patterns are risky because every clue gives more structure.'],
    previewSteps: ['Set code', 'Read clues', 'Crack first'],
    variants: [
      {
        id: 'digits',
        name: '4-Digit Code',
        icon: 'code-guess-digits',
        desc: 'Set a secret 4-digit code and crack your opponent first.',
        path: '/games/code-guess',
        previewSteps: ['Lock code', 'Guess digits', 'Use clues'],
      },
      {
        id: 'number-range',
        name: 'Number Range',
        icon: 'code-guess-number-range',
        desc: 'Both players lock a secret 1-100 number, then guess the opponent target with greater/less clues.',
        path: '/games/code-guess/number',
        rulesTitle: 'Number Range Rules',
        rules: ['Each player secretly locks one number in the allowed range.', 'On your turn, guess the number chosen by your opponent.', 'Each hint narrows your personal range higher or lower.', 'Find the opponent number first to win.'],
        tips: ['Middle guesses are steady, but off-center guesses can steal tempo.', 'Track your own narrowed range; your opponent has a separate one.'],
        previewSteps: ['Lock number', 'Guess target', 'Use clues'],
      },
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '5-10 min',
    tags: ['logic', 'puzzles', 'couples'],
    featured: true,
  },
  {
    id: 'memory-flip',
    gameType: 'memory_flip',
    name: 'Sequence Memory Flip',
    icon: 'memory-flip',
    description: 'Flip cards 1-9 in order. Wrong flip gives your opponent a chance.',
    players: '2 Players',
    category: 'Memory',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
    rulesTitle: 'Memory Flip Rules',
    rules: ['Find the next number in sequence, starting at 1.', 'Correct cards stay revealed.', 'A wrong flip ends your turn.', 'Complete the sequence first to win.'],
    tips: ['Say the revealed locations quietly in order after each turn.', 'A wrong guess still teaches both players, so watch opponent misses.'],
    previewSteps: ['Flip card', 'Remember spot', 'Run sequence'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '3-5 min',
    tags: ['memory', 'quick', 'couples'],
    featured: false,
  },
  {
    id: 'higher-lower',
    gameType: 'higher_lower',
    name: 'Higher or Lower Variants',
    icon: 'higher-lower',
    description: 'Both players lock secret numbers across Sprint, Classic, or Expert ranges, then guess head-to-head.',
    players: '2 Players',
    category: 'Quick',
    badgeClass: 'badge-green',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    rulesTitle: 'Higher or Lower Rules',
    rules: ['Each player secretly locks one number in the variant range.', 'On your turn, guess the number chosen by your opponent.', 'Each hint tells you whether the opponent number is higher or lower.', 'Your personal range shrinks after every miss.', 'Find the exact number first to win.'],
    tips: ['Use your range bar, not the original max, when choosing.', 'A narrow miss can hand the next player an easy finish.', 'Your range and your opponent\'s range can diverge quickly.'],
    previewSteps: ['Lock number', 'Guess target', 'Shrink range'],
    variants: [
      { id: 'sprint', name: 'Sprint', icon: 'higher-lower-sprint', desc: 'A compact 1-50 range for quick rounds.', path: '/games/higher-lower/sprint', previewSteps: ['Fast range', 'Quick hints', 'Exact hit'] },
      { id: 'classic', name: 'Classic', icon: 'higher-lower-classic', desc: 'The familiar 1-100 guessing window.', path: '/games/higher-lower', previewSteps: ['1-100', 'Narrow down', 'Win'] },
      { id: 'expert', name: 'Expert', icon: 'higher-lower-expert', desc: 'A wider 1-200 range with more pressure.', path: '/games/higher-lower/expert', previewSteps: ['Wide range', 'Sharper reads', 'Exact hit'] },
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '2-4 min',
    tags: ['quick', 'numbers'],
    featured: false,
  },
  {
    id: 'stop-clock',
    gameType: 'stop_clock',
    name: 'The 20-Second Challenge',
    icon: 'stop-clock',
    description: 'Start the timer and stop it at exactly 20 seconds. Closest wins.',
    players: '2 Players',
    category: 'Reflex',
    badgeClass: 'badge-blue',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    rulesTitle: 'Stop Clock Rules',
    rules: ['Both players ready up before the round starts.', 'Start your timer, then it hides after 3 seconds.', 'Stop as close to 20.00 seconds as possible.', 'Closest time wins.'],
    tips: ['Count in steady chunks instead of chasing the hidden timer.', 'Stopping early by a little is often safer than drifting late.'],
    previewSteps: ['Ready up', 'Timer hides', 'Stop close'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '1-2 min',
    tags: ['reflex', 'quick', 'timing'],
    featured: true,
  },
  {
    id: 'bluff-card',
    gameType: 'bluff_card',
    name: 'Bluff Card Game',
    icon: 'bluff-card',
    description: 'Play cards face down, claim the current rank, and decide when to call bluff.',
    players: '2 Players',
    category: 'Cards',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #7c3aed 0%, #be123c 100%)',
    rulesTitle: 'Bluff Rules',
    rules: ['The claim rank moves from A through K and repeats.', 'On your turn, play 1 to 4 cards face down as the current rank.', 'Your opponent may call bluff before playing.', 'If the play was false, the bluffer takes the pile; if it was honest, the challenger takes it.', 'First player to empty their hand wins.'],
    tips: ['Small honest plays make later bluffs more believable.', 'Call bluff when the claimed rank conflicts with cards you already hold.', 'A big pile is worth challenging only when you have a strong read.'],
    previewSteps: ['Claim rank', 'Play face down', 'Call bluff'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '5-10 min',
    tags: ['cards', 'bluffing', 'couples'],
    featured: false,
  },
  {
    id: 'checkers',
    gameType: 'checkers',
    name: 'Checkers Variants',
    icon: 'checkers',
    description: 'Play classic checkers or tactical twists with mines, VIP pieces, portals, and infection captures.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-blue',
    gradient: 'linear-gradient(135deg, #0369a1 0%, #0ea5e9 100%)',
    rulesTitle: 'Checkers Rules',
    rules: ['Move diagonally on dark squares toward the opposite side.', 'Jump an adjacent opponent piece to capture it.', 'If any capture is available, you must take a capture.', 'Reach the far side to crown a king that can move both directions.', 'Remove all opponent moves or pieces to win.'],
    tips: ['Keep back-row guards until you can crown safely.', 'Build trades that force the capture sequence you want.', 'Kings are tempo engines; protect the path to promotion.'],
    previewSteps: ['Move diagonally', 'Force jumps', 'Crown kings'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'checkers-classic', desc: 'Standard capture-and-crown checkers.', path: '/games/checkers', previewSteps: ['Advance', 'Jump', 'Crown'] },
      { id: 'anti', name: 'Anti-Checkers', icon: 'checkers-anti', desc: 'Losing all pieces or running out of moves wins.', path: '/games/checkers/anti', rulesTitle: 'Anti-Checkers Rules', rules: ['Normal movement and forced captures still apply.', 'If you lose all pieces or cannot move, you win instead of lose.', 'Use sacrifices to empty your side before your opponent can do the same.'], tips: ['Offer captures that leave your opponent with awkward material.', 'Avoid crowning unless it helps you shed pieces faster.'], previewSteps: ['Sacrifice', 'Force takes', 'Empty first'] },
      { id: 'zombie', name: 'Zombie Checkers', icon: 'checkers-zombie', desc: 'Captured pieces convert to your side instead of leaving the board.', path: '/games/checkers/zombie', rulesTitle: 'Zombie Rules', rules: ['Jumped pieces become yours instead of being removed.', 'Converted pieces can be used on later turns.', 'Win by taking over the board or trapping the opponent.'], tips: ['Chain conversions near the center for maximum reach.', 'A bad capture can hand the opponent a stronger army.'], previewSteps: ['Jump', 'Convert', 'Swarm'] },
      { id: 'minefield', name: 'Minefield', icon: 'checkers-minefield', desc: 'Both players secretly place traps before the first move.', path: '/games/checkers/minefield', rulesTitle: 'Minefield Rules', rules: ['Before play, each player secretly marks up to three mine squares.', 'When an opponent lands on your mine, the landing area explodes.', 'Explosions remove nearby pieces and clear the mine.'], tips: ['Put mines where forced jumps are likely to end.', 'Leave yourself escape squares around suspected traps.'], previewSteps: ['Hide mines', 'Lure jumps', 'Trigger blast'] },
      { id: 'vip', name: 'VIP', icon: 'checkers-vip', desc: 'Choose one secret protected piece; capturing it wins instantly.', path: '/games/checkers/vip', rulesTitle: 'VIP Rules', rules: ['Before play, each player secretly chooses one of their pieces as VIP.', 'Capturing the opposing VIP wins immediately.', 'VIP identity is hidden from the opponent until it matters.'], tips: ['Move decoys like they matter.', 'Do not strand your VIP without a trade route.'], previewSteps: ['Choose VIP', 'Hide intent', 'Capture target'] },
      { id: 'portal', name: 'Portal', icon: 'checkers-portal', desc: 'Landing on paired portal squares teleports the moving piece.', path: '/games/checkers/portal', rulesTitle: 'Portal Rules', rules: ['Portal squares appear in pairs near the center.', 'A piece that lands on a portal moves to its paired portal.', 'Portal travel ends the jump sequence for that turn.'], tips: ['Use portals to dodge blocks or create sudden crowning routes.', 'Watch portal exits before forcing captures.'], previewSteps: ['Find portal', 'Teleport', 'Reposition'] },
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '8-15 min',
    tags: ['strategy', 'board', 'variants'],
    featured: true,
  },
  {
    id: 'drop-four',
    gameType: 'drop_four',
    name: 'Drop Four Chaos',
    icon: 'drop-four',
    description: 'Connect four in a vertical grid with detonations, popouts, flipped gravity, hidden cells, and heavy tokens.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #0e7490 0%, #22c55e 100%)',
    rulesTitle: 'Drop Four Rules',
    rules: ['Drop tokens into one of seven columns.', 'Tokens fall under the current gravity direction.', 'Connect four horizontally, vertically, or diagonally to win.', 'Full columns cannot accept more tokens.'],
    tips: ['Build threats in two directions so one block is not enough.', 'Middle columns create the most diagonal options.', 'Count what each drop gives your opponent on the next turn.'],
    previewSteps: ['Choose column', 'Drop token', 'Connect four'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'drop-four-classic', desc: 'Standard gravity-based four-in-a-row.', path: '/games/drop-four', previewSteps: ['Drop', 'Stack', 'Connect'] },
      { id: 'wrecking-ball', name: 'Wrecking Ball', icon: 'drop-four-wrecking-ball', desc: 'Each player gets one detonating token that removes adjacent pieces.', path: '/games/drop-four/wrecking-ball', rulesTitle: 'Wrecking Ball Rules', rules: ['Each player has one Wrecking Ball token.', 'It drops like normal, then removes itself and all adjacent tokens.', 'Gravity compacts the affected columns before wins are checked.'], tips: ['Use the blast to break a loaded center stack.', 'A detonation can accidentally create a line after gravity settles.'], previewSteps: ['Arm token', 'Detonate', 'Settle'] },
      { id: 'popout', name: 'PopOut', icon: 'drop-four-popout', desc: 'Remove one of your own bottom tokens instead of dropping.', path: '/games/drop-four/popout', rulesTitle: 'PopOut Rules', rules: ['On your turn, drop normally or pop one of your own bottom tokens.', 'The remaining pieces in that column slide down.', 'Wins are checked after the popout settles.'], tips: ['Popouts can turn old stacks into sudden diagonals.', 'Do not pop a support piece that gifts the opponent a line.'], previewSteps: ['Drop', 'Pop base', 'Shift line'] },
      { id: 'gravity-flip', name: 'Gravity Flip', icon: 'drop-four-gravity-flip', desc: 'Each player can invert the grid once.', path: '/games/drop-four/gravity-flip', rulesTitle: 'Gravity Flip Rules', rules: ['Each player has one Flip Gravity power.', 'Flipping turns the board upside down and reverses gravity.', 'The board compacts under the new gravity before wins are checked.'], tips: ['Flip when the opponent stack depends on old support.', 'Plan where your tokens land after inversion.'], previewSteps: ['Build', 'Flip', 'Reconnect'] },
      { id: 'battleship-drop', name: 'Battleship Drop', icon: 'drop-four-battleship-drop', desc: 'The lower half of the grid is masked until pieces rise above it.', path: '/games/drop-four/battleship-drop', rulesTitle: 'Battleship Drop Rules', rules: ['The lower half of the grid is hidden from both players.', 'Drops still resolve server-side with normal gravity.', 'Visible top cells reveal normally when stacks rise above the screen.'], tips: ['Track column counts carefully.', 'Use opponent hesitation as a memory clue.'], previewSteps: ['Drop blind', 'Remember stacks', 'Reveal top'] },
      { id: 'heavy-token', name: 'Heavy Token', icon: 'drop-four-heavy-token', desc: 'Each player gets one token that crushes the piece beneath it.', path: '/games/drop-four/heavy-token', rulesTitle: 'Heavy Token Rules', rules: ['Each player has one Heavy token.', 'When dropped, it crushes exactly one non-heavy token beneath it.', 'Heavy tokens cannot crush other Heavy tokens.'], tips: ['Save the heavy token for a defended column.', 'Crushing can open space and create a new landing pattern.'], previewSteps: ['Arm heavy', 'Crush', 'Connect'] },
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '5-12 min',
    tags: ['strategy', 'gravity', 'board'],
    featured: true,
  },
  {
    id: 'trivia-battle',
    gameType: 'trivia_battle',
    name: 'Trivia Battle',
    icon: 'trivia-battle',
    description: 'Compete in real-time fast-paced trivia. Multiple choice questions across science, history, and pop culture.',
    players: '3-4 Players',
    category: 'Party',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
    rulesTitle: 'Trivia Battle Rules',
    rules: ['Players answer multiple-choice questions simultaneously.', 'Faster correct answers award more points.', 'The player with the most points after 10 rounds wins.'],
    tips: ['Speed is important, but a wrong answer gives zero points.', 'Use double-score powerups wisely if available.'],
    previewSteps: ['Read question', 'Answer fast', 'Top scoreboard'],
    playerCount: 4,
    playerLabel: '3-4 Players',
    difficulty: 'easy',
    estimatedTime: '5-10 min',
    tags: ['party', 'quiz', 'friends'],
    featured: true,
  },
  {
    id: 'couples-truth-dare',
    gameType: 'couples_truth_dare',
    name: 'Couples Truth & Dare',
    icon: 'couples-truth-dare',
    description: 'An intimate and fun game for couples. Discover new things about your partner with tailored prompts and challenges.',
    players: '2 Players',
    category: 'Couples',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #f43f5e 0%, #be123c 100%)',
    rulesTitle: 'Couples Truth & Dare Rules',
    rules: ['Take turns choosing Truth or Dare.', 'Complete the card prompt honestly or perform the dare.', 'Rate each other\'s answers to earn couple points.'],
    tips: ['Answer honestly to build deeper connections.', 'Keep the mood lighthearted and fun.'],
    previewSteps: ['Truth or Dare', 'Read prompt', 'Share & bond'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '5-15 min',
    tags: ['couples', 'party', 'social'],
    featured: true,
    isComingSoon: true,
  },
  {
    id: 'row-call',
    gameType: 'row_call',
    name: 'Row Call',
    icon: 'row-call',
    description: 'Dictate your opponent\'s next move in this strategic 4x4 line-connecting game.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',
    rulesTitle: 'Row Call Rules',
    rules: [
      'Take turns placing tokens on the 4x4 grid (A-D, 1-4).',
      'The first player places a token anywhere and calls a Row or Column.',
      'The opponent MUST place their next token inside that called Row or Column.',
      'After placing their token, that player then calls a Row or Column for the other player\'s next move.',
      'You cannot call a Row or Column that is already completely full.',
      'Connect four of your tokens in a straight line (horizontally, vertically, or diagonally) to win.'
    ],
    tips: [
      'Block your opponent\'s threats while setting up your own 4-in-a-row.',
      'Call rows/columns where your opponent has no good moves or is forced to play in your threat line.',
      'Keep track of which rows and columns are close to full; they limit your opponent\'s exit options.'
    ],
    previewSteps: ['Place token', 'Call Row/Col', 'Force opponent'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '3-6 min',
    tags: ['strategy', 'couples', 'board'],
    featured: true,
  },
  {
    id: 'dice-grid',
    gameType: 'dice_grid',
    name: 'The Dice Grid',
    icon: 'dice-grid',
    description: 'Roll dice, map coordinates, and connect four of your symbols in a line.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
    rulesTitle: 'The Dice Grid Rules',
    rules: [
      'On your turn, roll two six-sided dice.',
      'The roll generates a coordinate pair (e.g. 4 and 1 lets you place at Row 4 Col 1 or Row 1 Col 4).',
      'Select and claim one empty coordinate matching your roll.',
      'Double rolls only offer one coordinate.',
      'If both coordinate options are occupied, your turn ends immediately without placement.',
      'First to connect four symbols in a straight line (horizontal, vertical, diagonal) wins.'
    ],
    tips: [
      'Always check both coordinate options to block your opponent or extend your own chain.',
      'Set up forks where two different rolls can complete your four-in-a-row.',
      'Double rolls (like 3-3) are restrictive but can secure key center coordinates.'
    ],
    previewSteps: ['Roll dice', 'Choose coordinate', 'Connect four'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'dice-grid-classic', desc: 'Standard 6x6 grid with coordinate selection.', path: '/games/dice-grid', previewSteps: ['Roll', 'Select', 'Align'] },
      { id: 'obstacles', name: 'Block Obstacles', icon: 'dice-grid-obstacles', desc: 'The grid starts with three random cells blocked by dark obstacles.', path: '/games/dice-grid/obstacles', rulesTitle: 'Obstacles Rules', rules: ['Three random grid spaces are blocked by obstacles at start.', 'Obstacles cannot be claimed by either player.', 'Connect four around the obstacles to win.'], tips: ['Use obstacles to divide the board and isolate your opponent.', 'Calculate routes that wrap around the blocked cells.'], previewSteps: ['Scramble board', 'Avoid obstacles', 'Build chain'] }
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '3-8 min',
    tags: ['strategy', 'dice', 'board'],
    featured: true,
  },
  {
    id: 'black-hole',
    gameType: 'black_hole',
    name: 'Black Hole',
    icon: 'black-hole',
    description: 'Place your tokens strategically in a pyramid to minimize the sum of your tokens touching the final Black Hole.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #4f46e5 100%)',
    rulesTitle: 'Black Hole Rules',
    rules: [
      'Each player has 10 tokens numbered 1 through 10.',
      'On your turn, place a token on an empty circle in the 21-circle pyramid board.',
      'Classic variant forces placing tokens in order (1, 2, ... 10). Chaos variant lets you choose which remaining token to play.',
      'After all 20 tokens are placed, the single remaining empty cell is filled with the Black Hole token.',
      'Your score is the sum of the values of your tokens directly adjacent to the Black Hole.',
      'The player with the LOWEST score wins!'
    ],
    tips: [
      'Place your high-value tokens (8, 9, 10) near the edges or corners where they are less likely to touch the final empty slot.',
      'Try to leave empty slots adjacent to your opponent\'s high tokens to force them into a high-scoring hazard.',
      'In Chaos variant, save low-value tokens for late-game placement next to potential Black Hole cells.'
    ],
    previewSteps: ['Place tokens', 'Leave one empty', 'Lowest adjacent sum wins'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'black-hole-classic', desc: 'Tokens must be placed sequentially from 1 to 10.', path: '/games/black-hole', previewSteps: ['Place 1..10', 'Spot empty cell', 'Sum adjacent'] },
      { id: 'chaos', name: 'Chaos', icon: 'black-hole-chaos', desc: 'Choose which remaining token from your hand to play on your turn.', path: '/games/black-hole/chaos', rulesTitle: 'Chaos Rules', rules: ['You can choose any remaining token from your hand (1-10) to place.', 'Turns alternate until all 20 tokens are played.', 'The final empty slot becomes the Black Hole. Lowest adjacent sum wins.'], tips: ['Keep track of which numbers your opponent has left.', 'Bait your opponent into placing high numbers early.'], previewSteps: ['Select token from hand', 'Place strategically', 'Sum adjacent'] }
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '4-8 min',
    tags: ['strategy', 'board', 'math'],
    featured: true,
  },
  {
    id: 'trappex',
    gameType: 'trappex',
    name: 'Trappex',
    icon: 'trappex',
    description: 'Place barriers in a grid to enclose and claim more squares than your opponent.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-blue',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    rulesTitle: 'Trappex Rules',
    rules: [
      'On your turn, place exactly one barrier in an empty slot between dots.',
      'Enclosing the fourth side of a square claims that box.',
      'Claiming a square awards you 1 point and an immediate bonus turn!',
      'The game ends when all available barrier slots are filled.',
      'The player who claims the most squares wins.'
    ],
    tips: [
      'Avoid placing the third wall of a square, as it allows your opponent to easily claim it.',
      'Look for chain-reaction opportunities where a single placement can complete multiple squares.',
      'Sacrifice small squares to secure control of larger corridors if it blocks your opponent.'
    ],
    previewSteps: ['Place barrier', 'Enclose square', 'Earn bonus turn'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'trappex-classic', desc: 'Standard 5x5 grid enclosure battle.', path: '/games/trappex', previewSteps: ['5x5 Grid', 'Place wall', 'Enclose'] },
      { id: 'quick', name: 'Quick Play', icon: 'trappex-quick', desc: 'A smaller 4x4 grid for fast-paced enclosure matches.', path: '/games/trappex/quick', rulesTitle: 'Quick Rules', rules: ['Played on a smaller 4x4 grid of squares.', 'Total of 40 placement segments. First to claim the majority of 16 cells wins.'], tips: ['The smaller board means conflicts happen immediately. Guard your corridors early.'], previewSteps: ['4x4 Grid', 'Place wall', 'Enclose'] },
      { id: 'obstacles', name: 'Obstacles', icon: 'trappex-obstacles', desc: 'The 5x5 grid starts with 3 random squares pre-blocked by obstacles.', path: '/games/trappex/obstacles', rulesTitle: 'Obstacles Rules', rules: ['Three random squares are pre-blocked by brick obstacles at start.', 'Their borders are pre-placed and cannot be clicked.', 'Pre-blocked squares cannot be claimed by either player.'], tips: ['Use pre-blocked boundaries to complete your adjacent squares safely.'], previewSteps: ['Obstacle blocks', 'Route around blocks', 'Enclose'] }
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '4-10 min',
    tags: ['strategy', 'board', 'enclosure'],
    featured: true,
  },
  {
    id: 'dr-eureka',
    gameType: 'dr_eureka',
    name: 'Dr. Eureka',
    icon: 'dr-eureka',
    description: 'Race to arrange colored chemical balls in test tubes by pouring them to match challenge formulas.',
    players: '2 Players',
    category: 'Racing',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #d946ef 100%)',
    rulesTitle: 'Dr. Eureka Rules',
    rules: [
      'Pour balls from tube to tube to recreate the target arrangement.',
      'You cannot touch the balls or drop them out of the tubes.',
      'A tube can hold at most 4 balls.',
      'The target card shows the goal combination in any column order.',
      'First to solve 5 formulas wins!'
    ],
    tips: [
      'Use the empty tube as a temporary buffer to swap ball orders.',
      'Look for the shortest sequence of transfers before you start pouring.',
      'In Stroop variant, ignore the ball colors and focus purely on the target ink or text word as commanded!'
    ],
    previewSteps: ['Look at card', 'Pour balls', 'Shout Eureka!'],
    variants: [
      { id: 'classic', name: 'Classic', icon: 'dr-eureka-classic', desc: 'Solve random color configurations as fast as you can.', path: '/games/dr-eureka', previewSteps: ['Classic colors', 'Speed sorting', 'Victory'] },
      { id: 'stroop', name: 'Stroop Royale', icon: 'dr-eureka-stroop', desc: 'Balls have misleading text names and colors. Match by text content or ink color!', path: '/games/dr-eureka/stroop', rulesTitle: 'Stroop Rules', rules: ['A matching constraint is shown: Match by Ball Color, Text Ink Color, or Word Content.', 'Compare the relevant attribute of your balls to match the target colors.'], tips: ['Slow down slightly to override your automatic reading reflex (Stroop effect).'], previewSteps: ['Read target mode', 'Override reflexes', 'Solve'] },
      { id: 'sequential', name: 'Sequential Stacking', icon: 'dr-eureka-sequential', desc: 'Stack numbered balls 1 to 6 in a single tube in target order.', path: '/games/dr-eureka/sequential', rulesTitle: 'Sequential Rules', rules: ['Stack all 6 numbered balls in one of your tubes in the target sequence.', 'The other two tubes must be empty to claim round completion.'], tips: ['Group numbers at the bottom of temporary tubes to flip their ordering.'], previewSteps: ['Check sequence', 'Stack numbers', 'Complete'] }
    ],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '4-8 min',
    tags: ['racing', 'logic', 'speed'],
    featured: true,
  },
  {
    id: 'smart-four',
    gameType: 'smart_four',
    name: 'Smart Four & Topple',
    icon: 'smart-four',
    description: 'Stack tokens on a 5x5 grid. Win by connecting four in 3D space, or test your balance in the wobbly physics-based Topple.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
    rulesTitle: 'Smart Four Rules',
    rules: [
      'Take turns stacking pieces in a 5x5 grid up to height 5.',
      'Classic 3D: Connect four tokens in a straight line in 3D space.',
      'Topple: Roll dice, place on designated rings, and avoid toppling the board.'
    ],
    tips: [
      'Watch the height axis closely in both variants.',
      'In Topple, check the center of mass bubble level indicators before placing.'
    ],
    previewSteps: ['Pick variant', 'Stack pieces', 'Check win/tilt'],
    variants: SMART_FOUR_VARIANTS,
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '3-8 min',
    tags: ['strategy', '3d', 'physics'],
    featured: true,
  },
  {
    id: 'ultimate-tic-tac-toe',
    gameType: 'ultimate_tic_tac_toe',
    name: 'Ultimate Tic-Tac-Toe',
    icon: 'ultimate-tic-tac-toe',
    description: 'Play Tic-Tac-Toe inside Tic-Tac-Toe! Win mini boards to secure squares and align three mini-board claims in a row.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    rulesTitle: 'Ultimate Tic-Tac-Toe Rules',
    rules: [
      'The board is a 3x3 layout of mini 3x3 Tic-Tac-Toe boards.',
      'Your move in a mini-board forces your opponent to play in the corresponding board of the 3x3 layout.',
      'If you are sent to a board that is already won or full, you get a FREE MOVE and can play anywhere.',
      'Align three in a row on a mini-board to win that square.',
      'Align three won squares in a row globally to win the ultimate game!'
    ],
    tips: [
      'Try not to send your opponent to a mini-board where they can win a square.',
      'Intentionally sacrifice a move to gain a free move elsewhere on the board.',
      'Control the center mini-board early as it is crucial for global diagonals and rows.'
    ],
    previewSteps: ['Place in mini-board', 'Redirect opponent', 'Claim big squares'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '5-12 min',
    tags: ['strategy', 'nested', 'classic'],
  },
  {
    id: 'giiker-bolt',
    gameType: 'giiker_bolt',
    name: 'Giiker Bolt Memory',
    icon: 'giiker-bolt',
    description: 'Replicate sequence patterns on a flashing 3x3 light-up grid. If you forget or input the wrong sequence, you lose!',
    players: '2 Players',
    category: 'Memory',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #a855f7 100%)',
    rulesTitle: 'Giiker Bolt Rules',
    rules: [
      'The board will flash a sequence of cells on the 3x3 grid.',
      'After the flashing finishes, the active player must tap the cells in the exact order shown.',
      'Successfully replicating the sequence passes the turn to the other player and increases the sequence length by 1.',
      'Making a wrong input immediately ends the game and awards victory to the other player!'
    ],
    tips: [
      'Focus on the shape or flow of the sequence instead of just remembering coordinates.',
      'Assign numbers to the 3x3 grid (1-9) to mentally recite the sequence.',
      'Keep a steady rhythm while inputting the sequence.'
    ],
    previewSteps: ['Watch flash', 'Replicate steps', 'Alternate turns'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '2-6 min',
    tags: ['memory', 'reflex', 'quick'],
  },
  {
    id: 'triple-cross',
    gameType: 'triple_cross',
    name: 'Triple Cross',
    icon: 'triple-cross',
    description: 'Slide discs into an 8x3 grid, pushing opponent pieces out. Cap rows with blockers and score lines of three.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #0ea5e9 0%, #0891b2 100%)',
    rulesTitle: 'Triple Cross Rules',
    rules: [
      'Alternate turns pushing standard colored discs into any of the 8 rows from either the Left or Right side.',
      'Existing pieces in the row shift. Pushing can eject discs on the opposite end, which return to the owner.',
      'Optional blocker: Place a blocker on either side of a full row (containing 3 discs) to lock it from being pushed.',
      'Each player has 12 discs and 4 blockers.',
      'Score 1 point for every vertical or diagonal line of 3 matching discs. Horizontal lines do NOT score.',
      'Game ends when both players have 0 discs or all rows are blocked. Highest score wins!'
    ],
    tips: [
      'Use blockers to secure rows where you have favorable vertical/diagonal disc connections.',
      'Shove opponent pieces out of the board to disrupt their alignment chains.',
      'Save your blockers for high-value vertical towers or defensive locks.'
    ],
    previewSteps: ['Push disc', 'Shift row', 'Lock blocker', 'Align three'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '6-12 min',
    tags: ['strategy', 'displacement', 'board'],
  },
  {
    id: 'dot-matrix',
    gameType: 'dot_matrix',
    name: 'The dot Matrix',
    icon: 'dot-matrix',
    description: 'A die-controlled Dots & Boxes game where players roll to determine the number of line segments they must place.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-orange',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    rulesTitle: 'The dot Matrix Rules',
    rules: [
      'Roll the 6-sided die to determine your line limit for the turn.',
      'You must place exactly that number of line segments on the 5x5 grid of dots.',
      'Enclosing the fourth side of a square claims that box for 1 point.',
      'Completing a box does NOT grant a bonus turn. Turn ends only when all lines are placed.',
      'The player who claims the most squares wins when all 40 slots are filled.'
    ],
    tips: [
      'Do not place the third wall of a square unless you have enough moves to complete it yourself.',
      'Use large die rolls to claim multiple squares in a row if corridors are open.',
      'Count remaining open lines to force your opponent into making dangerous moves.'
    ],
    previewSteps: ['Roll die', 'Draw lines', 'Claim boxes'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '4-8 min',
    tags: ['strategy', 'dice', 'enclosure'],
  },
  {
    id: 'sos-dot',
    gameType: 'sos_dot',
    name: 'SOS Dot Game',
    icon: 'sos-dot',
    description: 'Place S or O letters on a 6x6 grid. Complete SOS lines to score points and earn bonus turns.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
    rulesTitle: 'SOS Dot Game Rules',
    rules: [
      'On your turn, choose "S" or "O" and place it in any empty grid cell.',
      'If you form one or more horizontal, vertical, or diagonal "S-O-S" sequences, you earn 1 point per sequence.',
      'Forming an SOS sequence grants you an immediate bonus turn.',
      'The game ends when the board is full. The player with the highest score wins.'
    ],
    tips: [
      'Be careful placing an "O" between two empty cells, as the opponent can complete an SOS on both sides.',
      'Look for multiple overlapping SOS opportunities to chain high-scoring combos.',
      'Use your bonus turns to place letters defensively and avoid setting up the opponent.'
    ],
    previewSteps: ['Select S or O', 'Place on grid', 'Complete SOS'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '3-6 min',
    tags: ['strategy', 'board', 'combo'],
  },
  {
    id: 'line-crosser',
    gameType: 'line_crosser',
    name: 'Line Crosser',
    icon: 'line-crosser',
    description: 'Connect boundary dots to draw lines across the grid. Intersecting existing lines scores points.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    rulesTitle: 'Line Crosser Rules',
    rules: [
      'Alternate turns drawing a straight line between two unused perimeter dots (out of 16).',
      'Connecting a dot consumes it permanently. Each dot can only be used once.',
      'Intersecting an opponent\'s line scores +1 point.',
      'Intersecting one of your own lines scores +2 points.',
      'The game ends when 1 or fewer dots remain. The player with the highest score wins.'
    ],
    tips: [
      'Place early lines across the center to create a target zone for future crossings.',
      'Try to cross multiple of your own lines in a single move for a huge +2 points per crossing.',
      'Keep track of remaining dots to ensure you don\'t run out of connection options.'
    ],
    previewSteps: ['Select unused dots', 'Draw crossing line', 'Score intersections'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '3-7 min',
    tags: ['strategy', 'lines', 'geometry'],
  },
  {
    id: 'scrabble-slam',
    gameType: 'scrabble_slam',
    name: 'Scrabble Slam!',
    icon: 'scrabble-slam',
    description: 'Slam letter cards to change an active four-letter word as fast as you can. Real-time spelling race!',
    players: '2 Players',
    category: 'Speed',
    badgeClass: 'badge-orange',
    gradient: 'linear-gradient(135deg, #ea580c 0%, #c2410c 100%)',
    rulesTitle: 'Scrabble Slam! Rules',
    rules: [
      'Spell a new word by slamming a letter from your hand onto the active four-letter word.',
      'You can only change exactly one letter of the word at a time.',
      'The proposed word must be a valid 4-letter English word in our dictionary.',
      'Simultaneous play—no turns! Play as fast as you can.',
      'First player to empty their hand of cards wins.'
    ],
    tips: [
      'Plan your next transitions before dragging cards.',
      'Watch out for invalid words; they trigger a 1.2-second submission penalty lock.',
      'Be quick—the opponent might change the active word before you can drop your card!'
    ],
    previewSteps: ['Read active word', 'Pick matching card', 'Slam first'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '2-4 min',
    tags: ['speed', 'words', 'realtime'],
  },
  {
    id: 'hand-hunt',
    gameType: 'hand_hunt',
    name: 'Hand Hunt',
    icon: 'hand-hunt',
    description: 'Spot and click target numbers on a scattered circular board as fast as you can.',
    players: '2 Players',
    category: 'Reflex',
    badgeClass: 'badge-pink',
    gradient: 'linear-gradient(135deg, #d946ef 0%, #a21caf 100%)',
    rulesTitle: 'Hand Hunt Rules',
    rules: [
      'Look at the target number displayed at the top.',
      'Find and click its corresponding circle inside the scattered central board.',
      'Correct clicks stamp that number on your grid and update the target.',
      'Wrong clicks trigger a 1.5-second penalty lockout.',
      'First to find 18 target numbers wins the match.'
    ],
    tips: [
      'Concentrate on the target value and scan concentric circle perimeters.',
      'Avoid clicking randomly; the 1.5-second lockout is highly punitive.',
      'React immediately to spots—your opponent sees the same target!'
    ],
    previewSteps: ['Check target number', 'Spot in center', 'Click and stamp'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '3-5 min',
    tags: ['reflex', 'speed', 'realtime'],
  },
  {
    id: 'pengoloo',
    gameType: 'pengoloo',
    name: 'Pengoloo',
    icon: 'pengoloo',
    description: 'Roll colored dice and lift penguins to find matching eggs in this classic memory match game.',
    players: '2 Players',
    category: 'Memory',
    badgeClass: 'badge-blue',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    rulesTitle: 'Pengoloo Rules',
    rules: [
      'On your turn, roll the two colored dice.',
      'Lift exactly two penguins from the center of the board to reveal hidden eggs.',
      'If an egg color matches one of the rolled colors, you claim that penguin for your iceberg.',
      'Claiming at least one penguin grants you a bonus turn.',
      'First to claim 6 penguins to fill their iceberg board wins.'
    ],
    tips: [
      'Pay close attention to egg colors revealed on the opponent\'s turn.',
      'Try to match both rolled colors to maximize your penguin gains.',
      'Remember where claimed colors used to be in case they are rolled again.'
    ],
    previewSteps: ['Roll colored dice', 'Lift two penguins', 'Match and claim'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'easy',
    estimatedTime: '4-8 min',
    tags: ['memory', 'board', 'turn-based'],
  },
  {
    id: 'battle-flips',
    gameType: 'battle_flips',
    name: 'Battle Flips',
    icon: 'battle-flips',
    description: 'A tactical word guessing game. Deduce the opponent\'s secret word while managing the risk of double reveals.',
    players: '2 Players',
    category: 'Logic',
    badgeClass: 'badge-purple',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #d946ef 100%)',
    rulesTitle: 'Battle Flips Rules',
    rules: [
      'Set a secret word of 3 to 10 letters during the setup phase.',
      'On your turn, guess a single letter.',
      'If the letter is in the opponent\'s word, they reveal it.',
      'If the letter is in your own word, you must also reveal it to your opponent!',
      'Guessing an opponent\'s letter correctly awards a bonus turn.',
      'Deduce and guess the opponent\'s full word first to win!'
    ],
    tips: [
      'Vowels are high risk—they are in almost every word, so guessing them will likely reveal your own letters.',
      'Look at your own revealed letters to see what the opponent might deduce.',
      'Guess the full word only when you are highly confident; a miss passes your turn.'
    ],
    previewSteps: ['Choose secret word', 'Guess letters', 'Avoid double-reveals', 'Deduce secret word'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'hard',
    estimatedTime: '4-8 min',
    tags: ['logic', 'words', 'couples'],
  },
  {
    id: 'bowtie-matrix',
    gameType: 'bowtie_matrix',
    name: 'The Bowtie Matrix',
    icon: 'bowtie-matrix',
    description: 'A tactical abstract board game of movement and leaping captures played on a bowtie-shaped grid.',
    players: '2 Players',
    category: 'Strategy',
    badgeClass: 'badge-cyan',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0369a1 100%)',
    rulesTitle: 'The Bowtie Matrix Rules',
    rules: [
      'Move one of your pieces to an adjacent empty node along connecting lines.',
      'Capture an opponent piece by jumping over it to an empty node immediately beyond it.',
      'The jump must follow a straight line path.',
      'Control the central chokepoint to traverse between board triangles.',
      'Eliminate all opponent pieces or block them completely to win.'
    ],
    tips: [
      'Guard the center vertex—it connects both halves of the bowtie and controls all crossings.',
      'Avoid placing pieces where your opponent has an easy straight jump line.',
      'Keep your pieces supported in blocks of two to prevent isolated captures.'
    ],
    previewSteps: ['Position pieces', 'Slide adjacent nodes', 'Jump to capture', 'Block opponent'],
    playerCount: 2,
    playerLabel: '2 Players',
    difficulty: 'medium',
    estimatedTime: '5-12 min',
    tags: ['strategy', 'board', 'tactical'],
  },
];

const GAME_TYPE_TO_ID: Record<string, string> = {
  tic_tac_toe: 'tic-tac-toe',
  shut_the_box: 'shut-the-box',
  code_guess: 'code-guess',
  memory_flip: 'memory-flip',
  higher_lower: 'higher-lower',
  stop_clock: 'stop-clock',
  bluff_card: 'bluff-card',
  checkers: 'checkers',
  drop_four: 'drop-four',
  trivia_battle: 'trivia-battle',
  row_call: 'row-call',
  dice_grid: 'dice-grid',
  black_hole: 'black-hole',
  trappex: 'trappex',
  dr_eureka: 'dr-eureka',
  smart_four: 'smart-four',
  ultimate_tic_tac_toe: 'ultimate-tic-tac-toe',
  giiker_bolt: 'giiker-bolt',
  triple_cross: 'triple-cross',
  dot_matrix: 'dot-matrix',
  sos_dot: 'sos-dot',
  line_crosser: 'line-crosser',
  scrabble_slam: 'scrabble-slam',
  hand_hunt: 'hand-hunt',
  pengoloo: 'pengoloo',
  battle_flips: 'battle-flips',
  bowtie_matrix: 'bowtie-matrix',
};


export function getGameCatalogItem(gameTypeOrId: string | null | undefined) {
  if (!gameTypeOrId) return null;
  const id = GAME_TYPE_TO_ID[gameTypeOrId] || gameTypeOrId;
  return GAME_CATALOG.find((game) => game.id === id || game.gameType === gameTypeOrId) || null;
}

export function getGameInfo(gameTypeOrId: string | null | undefined, variant?: string | null) {
  const game = getGameCatalogItem(gameTypeOrId);
  if (!game) return null;

  if (game.gameType === 'higher_lower' && variant === 'code_breaker_number') {
    const codeBreaker = getGameCatalogItem('code_guess');
    const numberRange = codeBreaker?.variants?.find((item) => item.id === 'number-range');
    if (codeBreaker && numberRange) {
      return {
        ...codeBreaker,
        icon: numberRange.icon,
        rulesTitle: numberRange.rulesTitle || codeBreaker.rulesTitle,
        rules: numberRange.rules || codeBreaker.rules,
        tips: numberRange.tips || codeBreaker.tips,
        previewSteps: numberRange.previewSteps || codeBreaker.previewSteps,
      };
    }
  }

  const selectedVariant = game.variants?.find((item) => item.id === variant);
  if (!selectedVariant) return game;

  return {
    ...game,
    icon: selectedVariant.icon,
    rulesTitle: selectedVariant.rulesTitle || game.rulesTitle,
    rules: selectedVariant.rules || game.rules,
    tips: selectedVariant.tips || game.tips,
    previewSteps: selectedVariant.previewSteps || game.previewSteps,
  };
}